// projects/storefront/src/app/checkout/components/payment-method-section/payment-method-section.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ShippingAddressFormComponent, ShippingAddressData } from '../shipping-address-form/shipping-address-form.component';

@Component({
  selector: 'app-payment-method-section',
  standalone: true,
  imports: [CommonModule, ShippingAddressFormComponent],
  templateUrl: './payment-method-section.component.html',
  styleUrls: ['./payment-method-section.component.scss']
})
export class PaymentMethodSectionComponent {
  @Input() storedCard?: { last4: string; brand: string; };
  @Output() cardUpdate = new EventEmitter<{ last4: string; brand: string; }>();

  showBillingForm = false;
  isModalOpen = false;

  handleBillingSubmit(data: ShippingAddressData) {
    console.log('Billing address submitted:', data);
  }

  handleCardSave() {
    // In a real scenario, you'd get this data from the Tranzila iframe/callback
    this.cardUpdate.emit({ last4: '4242', brand: 'Visa' });
    this.isModalOpen = false;
  }
}
<section class="payment-method">
  <h2 class="payment-method__title">Payment Method</h2>
  <div class="payment-method__card">
    <div *ngIf="storedCard; else noCard" class="payment-method__card-details">
      <div class="payment-method__card-info">
        <!-- Icon: CreditCard -->
        <svg class="payment-method__card-icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="20" height="14" x="2" y="5" rx="2"/><line x1="2" x2="22" y1="10" y2="10"/></svg>
        <div>
          <p class="payment-method__card-brand">{{ storedCard.brand }} ending in {{ storedCard.last4 }}</p>
          <p class="payment-method__card-text">Your card is securely stored.</p>
        </div>
      </div>
      <button (click)="isModalOpen = true" class="btn btn--outline">Update Card</button>
    </div>
    <ng-template #noCard>
      <button (click)="isModalOpen = true" class="btn btn--default btn--full-width">
        <!-- Icon: PlusCircle -->
        <svg class="payment-method__add-icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M8 12h8"/><path d="M12 8v8"/></svg>
        Add Payment Method
      </button>
    </ng-template>
  </div>

  <h2 class="payment-method__title">Billing Address</h2>
  <div class="payment-method__billing-address">
    <div class="payment-method__billing-address-option">
      <input type="checkbox" id="sameAsShipping" [checked]="!showBillingForm" (change)="showBillingForm = !showBillingForm" />
      <label for="sameAsShipping">Billing address is the same as shipping</label>
    </div>
    <div *ngIf="showBillingForm" class="payment-method__billing-address-form" [class.visible]="showBillingForm">
        <app-shipping-address-form (formUpdate)="handleBillingSubmit($event)"></app-shipping-address-form>
    </div>
  </div>
</section>

<div *ngIf="isModalOpen" class="modal-overlay" (click)="isModalOpen = false">
  <div class="modal-content" (click)="$event.stopPropagation()">
    <div class="modal-header">
      <h3 class="modal-title">{{ storedCard ? 'Update' : 'Add' }} Payment Method</h3>
      <button (click)="isModalOpen = false" class="modal-close">&times;</button>
    </div>
    <div class="modal-body">
      <div class="tranzila-form">
        <p class="tranzila-form__text">Tranzila Secure PCI-Compliant Form</p>
        <div class="tranzila-form__inputs">
          <input class="tranzila-form__input" placeholder="Card Number" />
          <div class="tranzila-form__input-group">
            <input class="tranzila-form__input" placeholder="MM/YY" />
            <input class="tranzila-form__input" placeholder="CVC" />
          </div>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button (click)="isModalOpen = false" class="btn btn--secondary">Cancel</button>
      <button (click)="handleCardSave()" class="btn btn--primary">Save Card</button>
    </div>
  </div>
</div>

// src/components/generated/PaymentMethodSection.tsx
"use client";
import * as React from "react";
import { motion } from "framer-motion";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
  DialogClose,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { CreditCard, Lock, PlusCircle } from "lucide-react";
import ShippingAddressForm from "./ShippingAddressForm"; // Assuming this is in the same directory

export interface PaymentMethodSectionProps {
  storedCard?: {
    last4: string;
    brand: string;
  };
  onCardUpdate: (card: { last4: string; brand: string }) => void;
}

export default function PaymentMethodSection({
  storedCard,
  onCardUpdate,
}: PaymentMethodSectionProps) {
  const [showBillingForm, setShowBillingForm] = React.useState(false);
  const [isModalOpen, setIsModalOpen] = React.useState(false);

  // Dummy handler for the billing form
  const handleBillingSubmit = (data: any) => {
    console.log("Billing address submitted:", data);
  };

  // Dummy handler for simulated Tranzila popup
  const handleCardSave = () => {
    // In a real scenario, you'd get this data from the Tranzila iframe/callback
    onCardUpdate({ last4: "4242", brand: "Visa" });
    setIsModalOpen(false);
  };

  const CardBrandIcon = ({ brand }: { brand: string }) => {
    // In a real app, you might have specific icons for each brand
    return <CreditCard className="h-8 w-8 text-muted-foreground" />;
  };

  return (
    <section className="space-y-6">
      <h2 className="text-2xl font-semibold">Payment Method</h2>
      <div className="p-6 border rounded-lg bg-card">
        {storedCard ? (
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <CardBrandIcon brand={storedCard.brand} />
              <div>
                <p className="font-medium">
                  {storedCard.brand} ending in {storedCard.last4}
                </p>
                <p className="text-sm text-muted-foreground">
                  Your card is securely stored.
                </p>
              </div>
            </div>
            <Dialog open={isModalOpen} onOpenChange={setIsModalOpen}>
              <DialogTrigger asChild>
                <Button variant="outline">Update Card</Button>
              </DialogTrigger>
              <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                  <DialogTitle>Update Payment Method</DialogTitle>
                </DialogHeader>
                <div className="grid gap-4 py-4">
                  {/* This would be the Tranzila iframe container */}
                  <div className="p-4 border-2 border-dashed rounded-lg text-center">
                    <p className="text-muted-foreground mb-2">
                      Tranzila Secure PCI-Compliant Form
                    </p>
                    <div className="space-y-2">
                      <Input placeholder="Card Number" />
                      <div className="flex gap-2">
                        <Input placeholder="MM/YY" />
                        <Input placeholder="CVC" />
                      </div>
                    </div>
                  </div>
                </div>
                <DialogFooter>
                  <DialogClose asChild>
                    <Button type="button" variant="secondary">
                      Cancel
                    </Button>
                  </DialogClose>
                  <Button type="button" onClick={handleCardSave}>
                    Save Card
                  </Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>
        ) : (
          <Dialog open={isModalOpen} onOpenChange={setIsModalOpen}>
            <DialogTrigger asChild>
              <Button variant="default" className="w-full">
                <PlusCircle className="mr-2 h-4 w-4" /> Add Payment Method
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[425px]">
              <DialogHeader>
                <DialogTitle>Add Payment Method</DialogTitle>
              </DialogHeader>
              <div className="grid gap-4 py-4">
                <div className="p-4 border-2 border-dashed rounded-lg text-center">
                  <p className="text-muted-foreground mb-2">
                    Tranzila Secure PCI-Compliant Form
                  </p>
                  <div className="space-y-2">
                    <Input placeholder="Card Number" />
                    <div className="flex gap-2">
                      <Input placeholder="MM/YY" />
                      <Input placeholder="CVC" />
                    </div>
                  </div>
                </div>
              </div>
              <DialogFooter>
                <DialogClose asChild>
                  <Button type="button" variant="secondary">
                    Cancel
                  </Button>
                </DialogClose>
                <Button type="button" onClick={handleCardSave}>
                  Save Card
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        )}
      </div>
      <h2 className="text-2xl font-semibold">Billing Address</h2>
      <div className="space-y-4">
        <div className="flex items-center space-x-2">
          <Checkbox
            id="sameAsShipping"
            checked={!showBillingForm}
            onCheckedChange={(checked) => setShowBillingForm(!checked)}
          />
          <Label htmlFor="sameAsShipping">
            Billing address is the same as shipping
          </Label>
        </div>
        <motion.div
          initial={false}
          animate={{
            height: showBillingForm ? "auto" : 0,
            opacity: showBillingForm ? 1 : 0,
          }}
          className="overflow-hidden"
        >
          {showBillingForm && (
            <div className="pt-4">
              {/* Here we reuse the form, but would ideally pass props to change legend and remove fields */}
              <ShippingAddressForm onSubmit={handleBillingSubmit} />
            </div>
          )}
        </motion.div>
      </div>
    </section>
  );
}
