// projects/storefront/src/app/checkout/components/shipping-address-form/shipping-address-form.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';

export interface ShippingAddressData {
  fullName: string;
  email: string;
  phone: string;
  address1: string;
  address2?: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  newsletter: boolean;
  terms: boolean;
}

@Component({
  selector: 'app-shipping-address-form',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './shipping-address-form.component.html',
  styleUrls: ['./shipping-address-form.component.scss']
})
export class ShippingAddressFormComponent implements OnInit {
  @Input() initialValues?: Partial<ShippingAddressData>;
  @Output() formUpdate = new EventEmitter<ShippingAddressData>();

  form!: FormGroup;

  constructor(private fb: FormBuilder) {}

  ngOnInit(): void {
    this.form = this.fb.group({
      fullName: [this.initialValues?.fullName || '', Validators.required],
      email: [this.initialValues?.email || '', [Validators.required, Validators.email]],
      phone: [this.initialValues?.phone || '', Validators.required],
      address1: [this.initialValues?.address1 || '', Validators.required],
      address2: [this.initialValues?.address2 || ''],
      city: [this.initialValues?.city || '', Validators.required],
      state: [this.initialValues?.state || '', Validators.required],
      zip: [this.initialValues?.zip || '', Validators.required],
      country: [this.initialValues?.country || 'USA', Validators.required],
      newsletter: [this.initialValues?.newsletter || false],
      terms: [this.initialValues?.terms || false, Validators.requiredTrue]
    });

    this.form.valueChanges.subscribe(() => {
      this.onFormUpdate();
    });
  }

  onFormUpdate(): void {
    if (this.form.valid) {
      this.formUpdate.emit(this.form.value);
    } else {
      // Optionally mark fields as touched to show errors as user types
      // this.form.markAllAsTouched();
    }
  }
}
<form class="shipping-form" [formGroup]="form">
  <fieldset class="shipping-form__fieldset">
    <legend class="shipping-form__legend">Shipping Address</legend>
    <div class="shipping-form__grid">
      <div class="shipping-form__grid-item--full">
        <label class="shipping-form__label" for="fullName">Full Name</label>
        <div class="shipping-form__input-container">
          <svg class="shipping-form__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
          <input class="shipping-form__input" id="fullName" formControlName="fullName" placeholder="John Doe" />
        </div>
        <div class="shipping-form__error" *ngIf="form.get('fullName')?.invalid && form.get('fullName')?.touched">
          Full name is required.
        </div>
      </div>
      <div class="shipping-form__grid-item">
        <label class="shipping-form__label" for="email">Email Address</label>
        <div class="shipping-form__input-container">
          <svg class="shipping-form__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="4" width="20" height="16" rx="2"></rect><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"></path></svg>
          <input class="shipping-form__input" id="email" type="email" formControlName="email" placeholder="you@example.com" />
        </div>
        <div class="shipping-form__error" *ngIf="form.get('email')?.invalid && form.get('email')?.touched">
          <span *ngIf="form.get('email')?.errors?.['required']">Email is required.</span>
          <span *ngIf="form.get('email')?.errors?.['email']">Email is invalid.</span>
        </div>
      </div>
      <div class="shipping-form__grid-item">
        <label class="shipping-form__label" for="phone">Phone Number</label>
        <div class="shipping-form__input-container">
          <svg class="shipping-form__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
          <input class="shipping-form__input" id="phone" type="tel" formControlName="phone" placeholder="(123) 456-7890" />
        </div>
        <div class="shipping-form__error" *ngIf="form.get('phone')?.invalid && form.get('phone')?.touched">
          Phone number is required.
        </div>
      </div>
      <div class="shipping-form__grid-item--full">
        <label class="shipping-form__label" for="address1">Address Line 1</label>
        <div class="shipping-form__input-container">
          <svg class="shipping-form__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
          <input class="shipping-form__input" id="address1" formControlName="address1" placeholder="123 Main St" />
        </div>
        <div class="shipping-form__error" *ngIf="form.get('address1')?.invalid && form.get('address1')?.touched">
          Address is required.
        </div>
      </div>
      <div class="shipping-form__grid-item--full">
        <label class="shipping-form__label" for="address2">Address Line 2 (Optional)</label>
        <div class="shipping-form__input-container">
          <svg class="shipping-form__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="4" width="16" height="16" rx="2" ry="2"></rect><line x1="9" y1="9" x2="15" y2="15"></line><line x1="15" y1="9" x2="9" y2="15"></line></svg>
          <input class="shipping-form__input" id="address2" formControlName="address2" placeholder="Apt, suite, etc." />
        </div>
      </div>
      <div class="shipping-form__grid-item">
        <label class="shipping-form__label" for="city">City</label>
        <input class="shipping-form__input" id="city" formControlName="city" placeholder="Anytown" />
        <div class="shipping-form__error" *ngIf="form.get('city')?.invalid && form.get('city')?.touched">
          City is required.
        </div>
      </div>
      <div class="shipping-form__grid-item">
        <label class="shipping-form__label" for="state">State / Province</label>
        <input class="shipping-form__input" id="state" formControlName="state" placeholder="CA" />
        <div class="shipping-form__error" *ngIf="form.get('state')?.invalid && form.get('state')?.touched">
          State/Province is required.
        </div>
      </div>
      <div class="shipping-form__grid-item">
        <label class="shipping-form__label" for="zip">ZIP / Postal Code</label>
        <input class="shipping-form__input" id="zip" formControlName="zip" placeholder="12345" />
        <div class="shipping-form__error" *ngIf="form.get('zip')?.invalid && form.get('zip')?.touched">
          ZIP/Postal code is required.
        </div>
      </div>
      <div class="shipping-form__grid-item">
        <label class="shipping-form__label" for="country">Country</label>
        <select class="shipping-form__input" id="country" formControlName="country">
          <option value="USA">United States</option>
          <option value="CAN">Canada</option>
          <option value="MEX">Mexico</option>
          <option value="GBR">United Kingdom</option>
        </select>
      </div>
    </div>
  </fieldset>
  <div class="shipping-form__options">
    <div class="shipping-form__option">
      <input class="shipping-form__checkbox" type="checkbox" id="newsletter" formControlName="newsletter" />
      <label class="shipping-form__label" for="newsletter">
        Sign up for our newsletter for exclusive offers.
      </label>
    </div>
    <div class="shipping-form__option">
      <input class="shipping-form__checkbox" type="checkbox" id="terms" formControlName="terms" />
      <label class="shipping-form__label" for="terms">
        I agree to the <a class="shipping-form__link" href="#">Terms and Conditions</a>.
      </label>
      <div class="shipping-form__error" *ngIf="form.get('terms')?.invalid && form.get('terms')?.touched">
        You must agree to the terms.
      </div>
    </div>
  </div>
</form>

// src/components/generated/ShippingAddressForm.tsx
"use client";
import * as React from "react";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Mail, User, Phone, MapPin, Building, Globe } from "lucide-react";

export interface ShippingAddressFormProps {
  initialValues?: Partial<ShippingAddressData>;
  onSubmit: (data: ShippingAddressData) => void;
}

export interface ShippingAddressData {
  fullName: string;
  email: string;
  phone: string;
  address1: string;
  address2?: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  newsletter: boolean;
  terms: boolean;
}

export default function ShippingAddressForm({
  initialValues,
  onSubmit,
}: ShippingAddressFormProps) {
  const [formData, setFormData] = React.useState<ShippingAddressData>({
    fullName: initialValues?.fullName || "",
    email: initialValues?.email || "",
    phone: initialValues?.phone || "",
    address1: initialValues?.address1 || "",
    address2: initialValues?.address2 || "",
    city: initialValues?.city || "",
    state: initialValues?.state || "",
    zip: initialValues?.zip || "",
    country: initialValues?.country || "USA",
    newsletter: initialValues?.newsletter || false,
    terms: initialValues?.terms || false,
  });
  const [errors, setErrors] = React.useState<
    Partial<Record<keyof ShippingAddressData, string>>
  >({});

  const validate = (name: keyof ShippingAddressData, value: any) => {
    let error = "";
    switch (name) {
      case "fullName":
        if (!value) error = "Full name is required.";
        break;
      case "email":
        if (!value) error = "Email is required.";
        else if (!/\S+@\S+\.\S+/.test(value)) error = "Email is invalid.";
        break;
      case "phone":
        if (!value) error = "Phone number is required.";
        break;
      case "address1":
        if (!value) error = "Address is required.";
        break;
      case "city":
        if (!value) error = "City is required.";
        break;
      case "state":
        if (!value) error = "State/Province is required.";
        break;
      case "zip":
        if (!value) error = "ZIP/Postal code is required.";
        break;
      case "terms":
        if (!value) error = "You must agree to the terms.";
        break;
    }
    setErrors((prev) => ({ ...prev, [name]: error }));
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value, type, checked } = e.target;
    const val = type === "checkbox" ? checked : value;
    setFormData((prev) => ({ ...prev, [name]: val }));
    validate(name as keyof ShippingAddressData, val);
  };

  const handleSelectChange = (name: keyof ShippingAddressData, value: string) => {
    setFormData((prev) => ({ ...prev, [name]: value }));
    validate(name, value);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // Validate all fields on submit
    Object.keys(formData).forEach((key) => {
      validate(
        key as keyof ShippingAddressData,
        formData[key as keyof ShippingAddressData]
      );
    });

    if (Object.values(errors).every((x) => !x) && formData.terms) {
      onSubmit(formData);
    }
  };

  const ErrorMessage = ({ message }: { message?: string }) => (
    <AnimatePresence>
      {message && (
        <motion.p
          initial={{ opacity: 0, y: -5 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -5 }}
          className="text-sm text-destructive mt-1"
          aria-live="polite"
        >
          {message}
        </motion.p>
      )}
    </AnimatePresence>
  );

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <fieldset>
        <legend className="text-2xl font-semibold mb-4">
          Shipping Address
        </legend>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="md:col-span-2">
            <Label htmlFor="fullName">Full Name</Label>
            <div className="relative">
              <User className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <Input
                id="fullName"
                name="fullName"
                value={formData.fullName}
                onChange={handleChange}
                placeholder="John Doe"
                className="pl-10"
              />
            </div>
            <ErrorMessage message={errors.fullName} />
          </div>
          <div>
            <Label htmlFor="email">Email Address</Label>
            <div className="relative">
              <Mail className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <Input
                id="email"
                name="email"
                type="email"
                value={formData.email}
                onChange={handleChange}
                placeholder="you@example.com"
                className="pl-10"
              />
            </div>
            <ErrorMessage message={errors.email} />
          </div>
          <div>
            <Label htmlFor="phone">Phone Number</Label>
            <div className="relative">
              <Phone className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <Input
                id="phone"
                name="phone"
                type="tel"
                value={formData.phone}
                onChange={handleChange}
                placeholder="(123) 456-7890"
                className="pl-10"
              />
            </div>
            <ErrorMessage message={errors.phone} />
          </div>
          <div className="md:col-span-2">
            <Label htmlFor="address1">Address Line 1</Label>
            <div className="relative">
              <MapPin className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <Input
                id="address1"
                name="address1"
                value={formData.address1}
                onChange={handleChange}
                placeholder="123 Main St"
                className="pl-10"
              />
            </div>
            <ErrorMessage message={errors.address1} />
          </div>
          <div className="md:col-span-2">
            <Label htmlFor="address2">Address Line 2 (Optional)</Label>
            <div className="relative">
              <Building className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <Input
                id="address2"
                name="address2"
                value={formData.address2}
                onChange={handleChange}
                placeholder="Apt, suite, etc."
                className="pl-10"
              />
            </div>
          </div>
          <div>
            <Label htmlFor="city">City</Label>
            <Input
              id="city"
              name="city"
              value={formData.city}
              onChange={handleChange}
              placeholder="Anytown"
            />
            <ErrorMessage message={errors.city} />
          </div>
          <div>
            <Label htmlFor="state">State / Province</Label>
            <Input
              id="state"
              name="state"
              value={formData.state}
              onChange={handleChange}
              placeholder="CA"
            />
            <ErrorMessage message={errors.state} />
          </div>
          <div>
            <Label htmlFor="zip">ZIP / Postal Code</Label>
            <Input
              id="zip"
              name="zip"
              value={formData.zip}
              onChange={handleChange}
              placeholder="12345"
            />
            <ErrorMessage message={errors.zip} />
          </div>
          <div>
            <Label htmlFor="country">Country</Label>
            <Select
              name="country"
              value={formData.country}
              onValueChange={(value) => handleSelectChange("country", value)}
            >
              <SelectTrigger>
                <Globe className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
                <SelectValue placeholder="Select a country" className="pl-10" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="USA">United States</SelectItem>
                <SelectItem value="CAN">Canada</SelectItem>
                <SelectItem value="MEX">Mexico</SelectItem>
                <SelectItem value="GBR">United Kingdom</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      </fieldset>
      <div className="space-y-4">
        <div className="flex items-start space-x-3">
          <Checkbox
            id="newsletter"
            name="newsletter"
            checked={formData.newsletter}
            onCheckedChange={(checked) =>
              handleSelectChange("newsletter", checked ? "true" : "")
            }
          />
          <div className="grid gap-1.5 leading-none">
            <label
              htmlFor="newsletter"
              className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
            >
              Sign up for our newsletter for exclusive offers.
            </label>
          </div>
        </div>
        <div className="flex items-start space-x-3">
          <Checkbox
            id="terms"
            name="terms"
            checked={formData.terms}
            onCheckedChange={(checked) =>
              handleSelectChange("terms", checked ? "true" : "")
            }
          />
          <div className="grid gap-1.5 leading-none">
            <label
              htmlFor="terms"
              className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
            >
              I agree to the{" "}
              <a href="#" className="text-primary hover:underline">
                Terms and Conditions
              </a>
              .
            </label>
            <ErrorMessage message={errors.terms} />
          </div>
        </div>
      </div>
    </form>
  );
}
